# Generated by Django 5.0.2 on 2024-02-18 22:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('password1', models.CharField(max_length=70)),
                ('password2', models.CharField(max_length=70)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PredictedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nitrogen', models.CharField(max_length=30)),
                ('phosphorus', models.CharField(max_length=30)),
                ('pottasium', models.CharField(max_length=30)),
                ('temperature', models.CharField(max_length=30)),
                ('humidity', models.CharField(max_length=30)),
                ('ph', models.CharField(max_length=30)),
                ('rainfall', models.CharField(max_length=30)),
                ('recommended_crop', models.CharField(max_length=30)),
                ('prediction_date', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='projects.profile')),
            ],
        ),
    ]
