# Generated by Django 5.0.2 on 2024-02-19 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictDisease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LeafImage', models.ImageField(upload_to='images/')),
                ('predicted_disease', models.CharField(max_length=30)),
                ('prediction_date_leaf', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='projects.profile')),
            ],
        ),
    ]
