# Generated by Django 5.0.2 on 2024-02-20 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_predictdisease'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictdisease',
            name='LeafImage',
            field=models.ImageField(upload_to='leafimages/'),
        ),
    ]
